language: node_js
services:
  - elasticsearch
node_js:
  - "0.12"


script:
  - npm run coverage

after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

env:
  #- COVERALLS_PARALLEL=true
