language: node_js
services:
  - elasticsearch
node_js:
  - "0.12"


script:
  - npm run coverage

after_success:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"

env:
  - COVERALLS_PARALLEL=true
